pipeline {
    agent any
    stages {
        stage("Checkout") {
            steps { 
                git url: 'https://github.com/senHou/calculator.git', branch: 'main'
            }
        }
        stage("Build") {
            steps {
                sh "mvn clean install"
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
    }
}