pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps { 
                git url 'https://github.com/senHou/calculator.git', branch: 'main'
            }
        }
    }
}