pipeline {
    agent any
    stages {
        stage("Checkout") {
            steps { 
                git url: 'https://github.com/senHou/calculator.git', branch: 'main'
            }
        }
        stage("Compile") {
            steps {
                sh "./mvn compile"
            }
        }
        stage("Test") {
            steps {
                sh "./mvn test"
            }
        }
    }
}